### ISSUE TITLE
Landmine exploding in hands when you try leave interior.

### ISSUE THREAD

**Issue by andrzej2273** [wenright/LC_LootableLandmines#1] opened 2024-05-04 23:20 UTC
When I try to leave the interior through the main entrance or the fire exit with a landmine in hands, it almost always explodes. This is happening as client only propably. Im using FairAI v1.3.5 by TheFluff.

**Comment by wenright** [comment] 2024-05-05 15:46
Thanks for pointing this out! It may have been caused by the v50 update, not sure. The issue was occurring even without the FairAI mod so something must have changed.
Either way, this should be resolved in 1.3.0 from #2 
Lemme know if that didn't fix it for you.

**Closed as completed by wenright** 2024-05-05 15:46 UTC
